import {
  Home,
  Users,
  Package,
  Tag,
  DollarSign,
  ShoppingCart,
  Truck,
  Warehouse,
  FileText,
  UserCog,
  BarChart2,
  Settings,
  MapPin,
  Calendar,
  CreditCard,
  Receipt,
  Archive,
  PieChart,
  Target,
  CheckCircle,
  PackageCheck,
  Percent,
  BarChart,
  ClipboardList,
  MapPinCheck,
  RefreshCw,
  FileCheck,
  Users2,
  Wallet,
  LineChart,
  Download,
  Activity,
  TrendingDown,
  TrendingUp,
  FolderSync,
  Gift,
  MessageCircle,
  History,
  BookMarked,
  Smartphone,
  Building2,
  Clock,
  Briefcase,
  ReceiptIcon,
} from 'lucide-react';

/**
 * BDMTILES Sidebar Menu Configuration
 * Each section can have: id, title, icon, path, permission, hasSubmenu, modulePermissions, items
 * Items can be nested for sub-menus (e.g., Profit Analysis inside Reports)
 */

const menuConfig = {
  dashboard: {
    id: 'dashboard',
    title: 'Dashboard',
    icon: Home,
    path: '/dashboard',
    permission: 'dashboard.view',
  },
  system: {
    id: 'system',
    title: 'System Management',
    icon: Settings,
    hasSubmenu: true,
    modulePermissions: ['system.management', 'users.manage'],
    items: [
      {
        id: 'user-management',
        title: 'User Management',
        icon: Users,
        path: '/system/users',
        permission: 'users.manage',
      },
      {
        id: 'recycle-bin',
        title: 'Recycle Bin',
        icon: Archive,
        path: '/system/recycle-bin',
        permission: 'users.manage',
      },
      {
        id: 'notification-inbox',
        title: 'Notifications',
        icon: MessageCircle,
        path: '/notifications',
        permission: 'notification.inbox',
      },
      {
        id: 'notification-templates',
        title: 'Notification Templates',
        icon: FileText,
        path: '/system/notification-templates',
        permission: 'notification.manage',
        roles: ['super_admin', 'owner'],
      },
      {
        id: 'notification-settings',
        title: 'Notification Controls',
        icon: Settings,
        path: '/system/notification-settings',
        permission: 'notification.manage',
        roles: ['super_admin', 'owner'],
      },
      {
        id: 'access-policies',
        title: 'Access Policies',
        icon: Clock,
        path: '/system/access-policies',
        permission: 'access.policy.manage',
        roles: ['super_admin', 'owner'],
      },
    ],
  },
  masters: {
    id: 'masters',
    title: 'Master Management',
    icon: Package,
    hasSubmenu: true,
    modulePermissions: ['product.master', 'price.list', 'dealer.discounts', 'category.setup', 'dealer.type', 'dealer.category', 'expense.category', 'region.master', 'route.master', 'branch.master', 'warehouse.master', 'vehicle.master', 'dealer.master', 'customer.master', 'supplier.master'],
    items: [
      {
        id: 'product-master',
        title: 'Product Master',
        icon: Package,
        path: '/masters/products',
        permission: 'product.master',
      },
      {
        id: 'price-list',
        title: 'Price List',
        icon: Tag,
        path: '/masters/price-list',
        permission: 'price.list',
      },
      {
        id: 'dealer-product-pricing',
        title: 'Dealer Product Pricing',
        icon: DollarSign,
        path: '/masters/dealer-product-pricing',
        permission: 'dealer.discounts',
      },
      {
        id: 'category-master',
        title: 'Brand & Category Setup',
        icon: Archive,
        path: '/masters/categories',
        permission: 'category.setup',
      },
      {
        id: 'dealer-type',
        title: 'Dealer Type',
        icon: Users,
        path: '/masters/dealer-type',
        permission: 'dealer.type',
      },
      {
        id: 'dealer-category',
        title: 'Dealer Category',
        icon: Users,
        path: '/masters/dealer-category',
        permission: 'dealer.category',
      },
      {
        id: 'expense-category',
        title: 'Expense Category',
        icon: Wallet,
        path: '/masters/expense-category',
        permission: 'expense.category',
      },
      {
        id: 'region-master',
        title: 'Region Master',
        icon: MapPinCheck,
        path: '/masters/regions',
        permission: 'region.master',
      },
      {
        id: 'route-master',
        title: 'Route Master',
        icon: MapPin,
        path: '/masters/routes',
        permission: 'route.master',
      },
      {
        id: 'branch-master',
        title: 'Branch Master',
        icon: Building2,
        path: '/masters/branch-master',
        permission: 'branch.master',
      },
      {
        id: 'warehouse-master',
        title: 'Warehouse Master',
        icon: Warehouse,
        path: '/masters/warehouse-master',
        permission: 'warehouse.master',
      },
      {
        id: 'vehicle-master',
        title: 'Vehicle Master',
        icon: Truck,
        path: '/masters/vehicles',
        permission: 'vehicle.master',
      },
      {
        id: 'dealer-master',
        title: 'Dealer Master',
        icon: Users,
        path: '/masters/dealers',
        permission: 'dealer.master',
      },
      {
        id: 'supplier-master',
        title: 'Supplier Master',
        icon: Building2,
        path: '/masters/suppliers',
        permission: 'supplier.master',
      },
      {
        id: 'customer-master',
        title: 'Customer Master',
        icon: Users,
        path: '/masters/customers',
        permission: 'customer.master',
      },
    ],
  },
  salesPurchase: {
    id: 'sales-purchase',
    title: 'Sales & Purchase',
    icon: ShoppingCart,
    hasSubmenu: true,
    modulePermissions: ['sales.order.dashboard', 'sales.order.create', 'sales.order.approve', 'quotation.management', 'dealer.discounts', 'po.management', 'po.approve', 'grn.entry', 'invoice', 'payment', 'credit.note', 'debit.note'],
    items: [
      {
        id: 'sales-order-dashboard',
        title: 'Sales Order Dashboard',
        icon: BarChart,
        path: '/sales-purchase/sales-order-dashboard',
        permission: 'sales.order.dashboard',
      },
      {
        id: 'quotation-manager',
        title: 'Quotation Manager',
        icon: FileText,
        path: '/sales-purchase/quotation-manager',
        permission: 'quotation.management',
      },
      {
        id: 'discount-mapping',
        title: 'Discount Mapping',
        icon: Percent,
        path: '/sales-purchase/discount-mapping',
        permission: 'dealer.discounts',
      },
      {
        id: 'po-management',
        title: 'PO Management',
        icon: FileText,
        path: '/sales-purchase/po-management',
        permissions: ['po.management', 'po.approve'],
      },
      {
        id: 'purchase-requisition',
        title: 'Purchase Requisition',
        icon: ClipboardList,
        path: '/sales-purchase/purchase-requisition',
        permissions: ['po.management', 'po.approve'],
      },
      {
        id: 'supplier-quotations',
        title: 'Supplier Quotations',
        icon: FileCheck,
        path: '/sales-purchase/supplier-quotations',
        permissions: ['po.management', 'po.approve'],
      },
      {
        id: 'grn-entry',
        title: 'GRN Entry',
        icon: PackageCheck,
        path: '/sales-purchase/grn-entry',
        permission: 'grn.entry',
      },
      {
        id: 'dealer-invoice',
        title: 'Invoices & Billing',
        icon: Receipt,
        path: '/sales-purchase/invoices',
        permission: 'invoice',
      },
      {
        id: 'supplier-invoice',
        title: 'Supplier Invoice',
        icon: ReceiptIcon,
        path: '/sales-purchase/supplier-invoice',
        permission: 'invoice',
      },
      {
        id: 'supplier-payments',
        title: 'Supplier Payments',
        icon: CreditCard,
        path: '/sales-purchase/supplier-payments',
        permission: 'payment',
      },
      {
        id: 'dealer-payments',
        title: 'Dealer Payments',
        icon: CreditCard,
        path: '/sales-purchase/dealer-payments',
        permission: 'payment',
      },
      {
        id: 'credit-note',
        title: 'Credit Note / Sales Return',
        icon: FileText,
        path: '/sales-purchase/credit-note',
        permission: 'credit.note',
      },
      {
        id: 'purchase-return',
        title: 'Purchase Returns / Debit Notes',
        icon: RefreshCw,
        path: '/sales-purchase/purchase-return',
        permission: 'debit.note',
      },
    ],
  },
  inventory: {
    id: 'inventory',
    title: 'Inventory & Warehouse',
    icon: Warehouse,
    hasSubmenu: true,
    modulePermissions: ['inventory.management', 'stock', 'stock.transfer'],
    items: [
      {
        id: 'stock',
        title: 'Stock Dashboard',
        icon: FolderSync,
        path: '/inventory/stock',
        permission: 'stock.view',
      },
      {
        id: 'stock-transfer',
        title: 'Stock Transfer',
        icon: RefreshCw,
        path: '/inventory/stock-transfers',
        permission: 'stock.transfer',
      },
      {
        id: 'stock-adjustment',
        title: 'Stock Adjustment',
        icon: RefreshCw,
        path: '/inventory/stock-adjustment',
        permission: 'stock.adjustment',
      },
      {
        id: 'physical-audit',
        title: 'Physical Audit',
        icon: CheckCircle,
        path: '/inventory/physical-audit',
        permission: 'stock.adjustment',
      },
      {
        id: 'stock-alerts',
        title: 'Stock Alerts',
        icon: Activity,
        path: '/inventory/stock-alerts',
        permission: 'stock.view',
      },
      {
        id: 'barcode-labels',
        title: 'Barcode & Labels',
        icon: Activity,
        path: '/inventory/barcode-labels',
        permission: 'stock.view',
      },
      {
        id: 'sample-management',
        title: 'Sample Management',
        icon: Package,
        path: '/inventory/samples',
        permission: 'stock.view',
      },
    ],
  },
  warehouse: {
    id: 'warehouse',
    title: 'Warehouse Operations',
    icon: PackageCheck,
    hasSubmenu: true,
    modulePermissions: ['picking.management', 'sorting.management', 'dispatch.management', 'warehouse.verification'],
    items: [
      {
        id: 'warehouse-complaint-verification',
        title: 'Complaint Verification',
        icon: FileCheck,
        path: '/complaints/warehouse-queue',
        permission: 'warehouse.verification',
      },
      {
        id: 'picking-list',
        title: 'Picking List',
        icon: ClipboardList,
        path: '/warehouse/picking-list',
        permission: 'picking.management',
      },
      {
        id: 'sorting-list',
        title: 'Sorting List',
        icon: ClipboardList,
        path: '/warehouse/sorting-list',
        permission: 'sorting.management',
      },
      {
        id: 'loading-verification',
        title: 'Loading Verification',
        icon: CheckCircle,
        path: '/warehouse/loading-verification',
        permission: 'dispatch.management',
      },
      {
        id: 'dispatch-planning',
        title: 'Dispatch Planning',
        icon: Truck,
        path: '/warehouse/dispatch-planning',
        permission: 'dispatch.management',
      },
    ],
  },
  dispatch: {
    id: 'dispatch',
    title: 'Dispatch & Delivery',
    icon: Truck,
    hasSubmenu: true,
    modulePermissions: ['dispatch.management', 'delivery.view', 'delivery.tracking'],
    items: [
      {
        id: 'delivery-assignment',
        title: 'Delivery Assignment',
        icon: CheckCircle,
        path: '/dispatch/delivery-assignment',
        permission: 'dispatch.management',
      },
      {
        id: 'delivery-monitoring',
        title: 'Delivery Tracking',
        icon: Activity,
        path: '/warehouse/delivery-tracking',
        permissions: ['delivery.view', 'delivery.tracking'],
      },
      {
        id: 'delivery-history',
        title: 'Delivery History',
        icon: History,
        path: '/dispatch/delivery-history',
        permission: 'dispatch.management',
      },
      {
        id: 'live-tracking',
        title: 'Live Tracking',
        icon: MapPin,
        path: '/dispatch/live-tracking',
        permission: 'dispatch.management',
      },
      {
        id: 'route-optimization',
        title: 'Route Optimization',
        icon: MapPinCheck,
        path: '/dispatch/route-optimization',
        permission: 'dispatch.management',
      },
    ],
  },
  crm: {
    id: 'crm',
    title: 'CRM',
    icon: Users2,
    hasSubmenu: true,
    modulePermissions: ['lead.view', 'lead.followup', 'lead.app'],
    items: [
      {
        id: 'my-leads',
        title: 'My Leads',
        icon: Smartphone,
        path: '/se-app/leads',
        permission: 'lead.app',
      },
      {
        id: 'lead-management',
        title: 'Lead Management',
        icon: Target,
        path: '/crm/lead-management',
        permission: 'lead.view',
      },
      {
        id: 'followup-manager',
        title: 'Follow-Up Manager',
        icon: Calendar,
        path: '/crm/followup-manager',
        permission: 'lead.followup',
      },
      {
        id: 'customer-360',
        title: 'Customer 360',
        icon: Users,
        path: '/crm/customer-360',
        permission: 'lead.view',
      },
    ],
  },
  complaints: {
    id: 'complaints',
    title: 'Complaints & Returns',
    icon: MessageCircle,
    hasSubmenu: true,
    modulePermissions: ['complaint.management'],
    items: [
      {
        id: 'complaint-dashboard',
        title: 'Complaint Dashboard',
        icon: Activity,
        path: '/complaints/dashboard',
        permission: 'complaint.management',
      },
      {
        id: 'return-request',
        title: 'Return Requests',
        icon: RefreshCw,
        path: '/complaints/return-request',
        permission: 'complaint.management',
      },
    ],
  },
  assets: {
    id: 'assets',
    title: 'Assets',
    icon: Briefcase,
    hasSubmenu: true,
    modulePermissions: ['asset.management'],
    items: [
      {
        id: 'asset-master',
        title: 'Asset Master',
        icon: Briefcase,
        path: '/assets/master',
        permission: 'asset.management',
      },
      {
        id: 'asset-assignment',
        title: 'Asset Assignment',
        icon: Users,
        path: '/assets/assignment',
        permission: 'asset.management',
      },
      {
        id: 'asset-maintenance',
        title: 'Maintenance',
        icon: RefreshCw,
        path: '/assets/maintenance',
        permission: 'asset.management',
      },
    ],
  },
  hrms: {
    id: 'hrms',
    title: 'HRMS Administration',
    icon: UserCog,
    hasSubmenu: true,
    modulePermissions: ['hrms.management', 'employee.registration', 'attendance.master'],
    items: [
      {
        id: 'employee-registration',
        title: 'Employee Registration',
        icon: ClipboardList,
        path: '/hrms/employee-registration',
        permission: 'employee.registration',
      },
      {
        id: 'geo-attendance',
        title: 'Geo Attendance',
        icon: MapPinCheck,
        path: '/hrms/geo-attendance',
        permission: 'attendance.master',
      },
      {
        id: 'attendance-master',
        title: 'Attendance Master',
        icon: Calendar,
        path: '/hrms/attendance-master',
        permission: 'attendance.master',
      },
      {
        id: 'shift-management',
        title: 'Shift Management',
        icon: Clock,
        path: '/hrms/shift-management',
        permission: 'attendance.master',
      },
      {
        id: 'leave-management',
        title: 'Leave Management',
        icon: Calendar,
        path: '/hrms/leave-management',
        permission: 'attendance.master',
      },
      {
        id: 'salary-processing',
        title: 'Salary Processing',
        icon: DollarSign,
        path: '/hrms/salary-processing',
        permission: 'salary.management',
      },
      {
        id: 'generate-salary-slip',
        title: 'Generate Salary Slip',
        icon: Receipt,
        path: '/hrms/generate-salary-slip',
        permission: 'salary.management',
      },
      {
        id: 'loans-advances',
        title: 'Loans & Advances',
        icon: Wallet,
        path: '/hrms/loans-advances',
        permission: 'salary.management',
      },
      {
        id: 'overtime-calculation',
        title: 'Overtime Calculation',
        icon: Clock,
        path: '/hrms/overtime-calculation',
        permission: 'attendance.master',
      },
      {
        id: 'daily-wage-workers',
        title: 'Daily Wage Workers',
        icon: Users,
        path: '/hrms/daily-wage-workers',
        permission: 'attendance.master',
      },
      {
        id: 'hrms-settings',
        title: 'HRMS Settings',
        icon: Settings,
        path: '/hrms/settings',
        permission: 'hrms.management',
      },
    ],
  },
  finance: {
    id: 'finance',
    title: 'Finance & Accounts',
    icon: FileText,
    hasSubmenu: true,
    modulePermissions: ['finance.management', 'dealer.ledger', 'supplier.ledger'],
    items: [
      {
        id: 'finance-complaint-review',
        title: 'Complaint Finance Review',
        icon: CheckCircle,
        path: '/complaints/finance-queue',
        permission: 'finance.management',
      },
      {
        id: 'bank-account-master',
        title: 'Bank Account Master',
        icon: Building2,
        path: '/finance/bank-account-master',
        permission: 'finance.management',
      },
      {
        id: 'voucher-entry',
        title: 'Voucher Entry',
        icon: Receipt,
        path: '/finance/voucher-entry',
        permission: 'finance.management',
      },
      {
        id: 'account-master',
        title: 'Account Master',
        icon: BookMarked,
        path: '/finance/account-master',
        permission: 'finance.management',
      },
      {
        id: 'cash-bank-book',
        title: 'Cash/Bank Book',
        icon: Wallet,
        path: '/finance/cash-bank-book',
        permission: 'finance.management',
      },
      {
        id: 'dealer-ledger',
        title: 'Dealer Ledger',
        icon: Users2,
        path: '/finance/dealer-ledger',
        permission: 'dealer.ledger',
      },
      {
        id: 'supplier-ledger',
        title: 'Supplier Ledger',
        icon: Briefcase,
        path: '/finance/supplier-ledger',
        permission: 'supplier.ledger',
      },
      {
        id: 'cheque-management',
        title: 'Cheque Management',
        icon: FileCheck,
        path: '/finance/cheque-management',
        permission: 'cheque.view',
      },
      {
        id: 'auto-reconciliation',
        title: 'Auto Reconciliation',
        icon: RefreshCw,
        path: '/finance/bank-reconciliation',
        permission: 'reconciliation',
      },
      {
        id: 'credit-days-monitor',
        title: 'Credit Days Monitor',
        icon: Calendar,
        path: '/finance/credit-days-monitor',
        permission: 'finance.management',
      },
      {
        id: 'expense-management',
        title: 'Expense Management',
        icon: Receipt,
        path: '/finance/expense-management',
        permission: 'finance.management',
      },
    ],
  },
  reports: {
    id: 'reports',
    title: 'Reports & Logs',
    icon: BarChart2,
    hasSubmenu: true,
    modulePermissions: ['reports.sales', 'reports.purchase', 'reports.inventory', 'reports.finance', 'reports.profit', 'reports.gst', 'reports.hr', 'activity.logs', 'download.logs', 'audit.trail'],
    items: [
      {
        id: 'profit-analysis',
        title: 'Profit Analysis',
        icon: PieChart,
        hasSubmenu: true,
        modulePermissions: ['reports.profit'],
        items: [
          {
            id: 'bill-wise-profit',
            title: 'Bill-wise Profit',
            icon: FileText,
            path: '/reports/advanced',
            permission: 'reports.profit',
          },
          {
            id: 'category-margin',
            title: 'Category Margin',
            icon: BarChart2,
            path: '/reports/profit-analysis/category-margin',
            permission: 'reports.profit',
          },
          {
            id: 'deviation-report',
            title: 'Deviation Report',
            icon: TrendingDown,
            path: '/reports/profit-analysis/deviation-report',
            permission: 'reports.profit',
          },
        ],
      },
      {
        id: 'sales-reports',
        title: 'Sales Reports',
        icon: TrendingUp,
        path: '/reports/sales-reports',
        permission: 'reports.sales',
      },
      {
        id: 'purchase-reports',
        title: 'Purchase Reports',
        icon: BarChart,
        path: '/reports/purchase-reports',
        permission: 'reports.purchase',
      },
      {
        id: 'inventory-reports',
        title: 'Inventory Reports',
        icon: Warehouse,
        path: '/reports/inventory-reports',
        permission: 'reports.inventory',
      },
      {
        id: 'hr-reports',
        title: 'HR Reports',
        icon: Users,
        path: '/reports/hr-reports',
        permission: 'reports.hr',
      },
      {
        id: 'dealer-performance',
        title: 'Dealer Performance',
        icon: LineChart,
        path: '/reports/dealer-performance',
        permission: 'reports.sales',
      },
      {
        id: 'se-performance',
        title: 'SE Performance',
        icon: Target,
        path: '/reports/se-performance',
        permission: 'reports.sales',
      },
      {
        id: 'gst-reports',
        title: 'GST Reports',
        icon: FileText,
        path: '/reports/gst-reports',
        permission: 'reports.gst',
      },
      {
        id: 'aging-report',
        title: 'Aging Report',
        icon: Clock,
        path: '/reports/aging-report',
        permission: 'reports.finance',
      },
      {
        id: 'balance-sheet',
        title: 'Balance Sheet',
        icon: FileText,
        path: '/reports/balance-sheet',
        permission: 'reports.finance',
      },
      {
        id: 'trial-balance',
        title: 'Trial Balance',
        icon: FileText,
        path: '/reports/trial-balance',
        permission: 'reports.finance',
      },
      {
        id: 'profit-loss',
        title: 'Profit & Loss',
        icon: FileText,
        path: '/reports/profit-loss',
        permission: 'reports.finance',
      },
      {
        id: 'cash-flow',
        title: 'Cash Flow',
        icon: Wallet,
        path: '/reports/cash-flow',
        permission: 'reports.finance',
      },
      {
        id: 'bank-reconciliation',
        title: 'Bank Reconciliation',
        icon: RefreshCw,
        path: '/reports/bank-reconciliation',
        permission: 'reports.finance',
      },
      {
        id: 'audit-trail',
        title: 'Audit Trail',
        icon: FileText,
        path: '/reports/audit-trail',
        permission: 'audit.trail',
      },
      {
        id: 'activity-logs',
        title: 'Activity Logs',
        icon: Activity,
        path: '/reports/activity-logs',
        permission: 'activity.logs',
      },
      {
        id: 'download-logs',
        title: 'Download Logs',
        icon: Download,
        path: '/reports/download-logs',
        permission: 'download.logs',
      },
    ],
  },
  // tally: {
  //   id: 'tally',
  //   title: 'Tally Integration',
  //   icon: FolderSync,
  //   hasSubmenu: true,
  //   modulePermissions: ['tally.sync'],
  //   items: [
  //     {
  //       id: 'tally-dashboard',
  //       title: 'Tally Dashboard',
  //       icon: BarChart2,
  //       path: '/tally/dashboard',
  //       permission: 'tally.sync',
  //     },
  //     {
  //       id: 'tally-sync-status',
  //       title: 'Sync Status',
  //       icon: RefreshCw,
  //       path: '/tally/sync-status',
  //       permission: 'tally.sync',
  //     },
  //     {
  //       id: 'tally-conflict-resolver',
  //       title: 'Conflict Resolver',
  //       icon: CheckCircle,
  //       path: '/tally/conflict-resolver',
  //       permission: 'tally.sync',
  //     },
  //   ],
  // },
  supplierIncentive: {
    id: 'supplier-incentive',
    title: 'Supplier Incentive',
    icon: Gift,
    hasSubmenu: true,
    modulePermissions: ['scheme.entry', 'scheme.analysis', 'claim.submission', 'incentive.reconciliation'],
    items: [
      {
        id: 'scheme-entry',
        title: 'Scheme Entry',
        icon: FileText,
        path: '/sales-purchase/supplier-schemes',
        permission: 'scheme.entry',
      },
      {
        id: 'scheme-analysis',
        title: 'Scheme Analysis',
        icon: BarChart2,
        path: '/supplier-incentive/scheme-analysis',
        permission: 'scheme.analysis',
      },
      {
        id: 'claim-submission',
        title: 'Claim Submission',
        icon: ClipboardList,
        path: '/supplier-incentive/claim-submission',
        permission: 'claim.submission',
      },
      {
        id: 'incentive-reconciliation',
        title: 'Reconciliation',
        icon: RefreshCw,
        path: '/supplier-incentive/reconciliation',
        permission: 'incentive.reconciliation',
      },
    ],
  },
  dealerSchemes: {
    id: 'dealer-schemes',
    title: 'Dealer Schemes',
    icon: Gift,
    hasSubmenu: true,
    modulePermissions: ['scheme.analysis'],
    items: [
      {
        id: 'dealer-scheme-setup',
        title: 'Scheme Setup',
        icon: Settings,
        path: '/dealer-app/scheme-setup',
        permission: 'scheme.analysis',
      },
      {
        id: 'dealer-points-tracker',
        title: 'Points Tracker',
        icon: Target,
        path: '/dealer-app/points-tracker',
        permission: 'scheme.analysis',
      },
    ],
  },
  approvals: {
    id: 'approvals',
    title: 'Approval Workflow',
    icon: CheckCircle,
    path: '/approvals',
    permission: 'dashboard.view',
  },
  dealerApp: {
    id: 'dealer-app',
    title: 'Dealer App',
    icon: Smartphone,
    hasSubmenu: true,
    modulePermissions: ['support.chat', 'dealer.order.requests'],
    items: [
      {
        id: 'dealer-support-chat',
        title: 'Support Chat',
        icon: MessageCircle,
        path: '/dealer-app/support-chat',
        permission: 'support.chat',
      },
      {
        id: 'dealer-order-requests',
        title: 'Dealer Order Requests',
        icon: ClipboardList,
        path: '/dealer-app/order-requests',
        permission: 'dealer.order.requests',
      },
    ],
  },
  salesExecutive: {
    id: 'sales-executive-app',
    title: 'Sales Executive App',
    icon: Users2,
    hasSubmenu: true,
    modulePermissions: ['sales.executive.app', 'se.attendance.view'],
    items: [
      {
        id: 'se-attendance',
        title: 'Attendance',
        icon: CheckCircle,
        path: '/se-app/attendance',
        permission: 'se.attendance.view',
      },
      {
        id: 'se-dealer-visits',
        title: 'Dealer Visits',
        icon: MapPinCheck,
        path: '/se-app/dealer-visits',
        permission: 'se.attendance.view',
      },
      {
        id: 'se-dealer-assignment',
        title: 'Dealer Assignment',
        icon: Users2,
        path: '/se-app/dealer-assignment',
        permission: 'se.attendance.view',
      },
      {
        id: 'se-route-plan',
        title: 'Route Plan',
        icon: MapPin,
        path: '/se-app/route-plan',
        permission: 'se.route.plan',
      },
      {
        id: 'se-dealer-insights',
        title: 'Dealer Insights',
        icon: TrendingUp,
        path: '/se-app/dealer-insights',
        permission: 'se.dealer.insights',
      },
      {
        id: 'se-collections',
        title: 'Collections',
        icon: Wallet,
        path: '/se-app/collections',
        permission: 'se.collections.view',
      },
      {
        id: 'se-targets',
        title: 'Targets',
        icon: Target,
        path: '/se-app/targets',
        permission: 'se.targets.view',
      },
      {
        id: 'se-expenses',
        title: 'Expenses',
        icon: Receipt,
        path: '/se-app/expenses',
        permission: 'sales.executive.app',
      },
      {
        id: 'se-live-tracking',
        title: 'Live Tracking',
        icon: MapPin,
        path: '/se-app/live-tracking',
        permission: 'sales.executive.app',
      },
    ],
  },
  deliveryExecutive: {
    id: 'delivery-executive-app',
    title: 'Delivery Executive App',
    icon: Truck,
    hasSubmenu: true,
    modulePermissions: ['delivery.executive.app', 'de.assignment.manage'],
    items: [
      {
        id: 'de-assignment',
        title: 'Assignment',
        icon: CheckCircle,
        path: '/de-app/assignment',
        permission: 'de.assignment.manage',
      },
      {
        id: 'de-monitoring',
        title: 'Monitoring',
        icon: Activity,
        path: '/de-app/monitoring',
        permission: 'de.monitoring.view',
      },
      {
        id: 'de-my-deliveries',
        title: 'My Deliveries',
        icon: Truck,
        path: '/de-app/my-deliveries',
        permission: 'de.deliveries.view',
      },
      {
        id: 'de-live-tracking',
        title: 'Live Tracking',
        icon: MapPin,
        path: '/de-app/live-tracking',
        permission: 'de.tracking.view',
      },
      {
        id: 'de-route-plan',
        title: 'Route Plan',
        icon: MapPinCheck,
        path: '/de-app/route-plan',
        permission: 'de.route.view',
      },
      {
        id: 'de-collections',
        title: 'Collections',
        icon: Wallet,
        path: '/de-app/collections',
        permission: 'de.collections.view',
      },
      {
        id: 'de-history',
        title: 'History',
        icon: History,
        path: '/de-app/history',
        permission: 'de.history.view',
      },
    ],
  },
};

/**
 * Role-based section visibility
 * super_admin sees all, others see relevant sections
 */
export const getRoleMenuSections = () => {
  const allSections = [
    menuConfig.dashboard,
    menuConfig.system,
    menuConfig.masters,
    menuConfig.salesPurchase,
    menuConfig.inventory,
    menuConfig.warehouse,
    menuConfig.dispatch,
    menuConfig.crm,
    menuConfig.complaints,
    menuConfig.assets,
    menuConfig.hrms,
    menuConfig.finance,
    menuConfig.reports,
    // menuConfig.tally,
    menuConfig.supplierIncentive,
    menuConfig.dealerSchemes,
    menuConfig.approvals,
    menuConfig.dealerApp,
    menuConfig.salesExecutive,
    menuConfig.deliveryExecutive,
  ];

  return allSections;
};

export default menuConfig;
