import {
  Home,
  Users,
  Package,
  Tag,
  DollarSign,
  ShoppingCart,
  Truck,
  Warehouse,
  FileText,
  UserCog,
  BarChart2,
  Settings,
  MapPin,
  Calendar,
  CreditCard,
  Receipt,
  Archive,
  PieChart,
  Target,
  CheckCircle,
  PackageCheck,
  Percent,
  BarChart,
  ClipboardList,
  MapPinCheck,
  RefreshCw,
  FileCheck,
  Users2,
  Wallet,
  LineChart,
  Download,
  Activity,
  TrendingDown,
  TrendingUp,
  FolderSync,
  Gift,
  MessageCircle,
  History,
  BookMarked,
  Smartphone,
  Building2,
  Clock,
  Briefcase,
  ReceiptIcon,
} from 'lucide-react';

/**
 * BDMTILES Sidebar Menu Configuration
 * Each section can have: id, title, icon, path, permission, hasSubmenu, modulePermissions, items
 * Items can be nested for sub-menus (e.g., Profit Analysis inside Reports)
 */

const menuConfig = {
  dashboard: {
    id: 'dashboard',
    title: 'Dashboard',
    icon: Home,
    path: '/dashboard',
    permission: 'dashboard.view',
  },
  system: {
    id: 'system',
    title: 'System Management',
    icon: Settings,
    hasSubmenu: true,
    modulePermissions: ['system.management', 'users.manage'],
    items: [
      {
        id: 'user-management',
        title: 'User Management',
        icon: Users,
        path: '/system/users',
        permission: 'users.manage',
      },
    ],
  },
  masters: {
    id: 'masters',
    title: 'Master Management',
    icon: Package,
    hasSubmenu: true,
    modulePermissions: ['master.management', 'product.master', 'dealer.master', 'supplier.master'],
    items: [
      {
        id: 'product-master',
        title: 'Product Master',
        icon: Package,
        path: '/masters/products',
        permission: 'product.master',
      },
      {
        id: 'price-list',
        title: 'Price List',
        icon: Tag,
        path: '/masters/price-list',
        permission: 'product.master',
      },
      {
        id: 'dealer-product-pricing',
        title: 'Dealer Product Pricing',
        icon: DollarSign,
        path: '/masters/dealer-product-pricing',
        permission: 'product.master',
      },
      {
        id: 'category-master',
        title: 'Brand & Category Setup',
        icon: Archive,
        path: '/masters/categories',
        permission: 'category.setup',
      },
      {
        id: 'dealer-type',
        title: 'Dealer Type',
        icon: Users,
        path: '/masters/dealer-type',
        permission: 'dealer.type',
      },
      {
        id: 'dealer-category',
        title: 'Dealer Category',
        icon: Users,
        path: '/masters/dealer-category',
        permission: 'dealer.category',
      },
      {
        id: 'expense-category',
        title: 'Expense Category',
        icon: Wallet,
        path: '/masters/expense-category',
        permission: 'expense.category',
      },
      {
        id: 'region-master',
        title: 'Region Master',
        icon: MapPinCheck,
        path: '/masters/regions',
        permission: 'region.master',
      },
      {
        id: 'route-master',
        title: 'Route Master',
        icon: MapPin,
        path: '/masters/routes',
        permission: 'route.master',
      },
      {
        id: 'warehouse-master',
        title: 'Warehouse Master',
        icon: Warehouse,
        path: '/masters/warehouse-master',
        permission: 'warehouse.master',
      },
      {
        id: 'dealer-master',
        title: 'Dealer Master',
        icon: Users,
        path: '/masters/dealers',
        permission: 'dealer.master',
      },
      {
        id: 'supplier-master',
        title: 'Supplier Master',
        icon: Building2,
        path: '/masters/suppliers',
        permission: 'supplier.master',
      },
    ],
  },
  salesPurchase: {
    id: 'sales-purchase',
    title: 'Sales & Purchase',
    icon: ShoppingCart,
    hasSubmenu: true,
    modulePermissions: ['sales.purchase.management', 'sales.order.dashboard', 'dealer.specific.discounts', 'po.management'],
    items: [
      {
        id: 'sales-order-dashboard',
        title: 'Sales Order Dashboard',
        icon: BarChart,
        path: '/sales-purchase/sales-order-dashboard',
        permission: 'sales.order.dashboard',
      },
      {
        id: 'dealer-discounts',
        title: 'Dealer Discounts',
        icon: Percent,
        path: '/sales-purchase/dealer-discounts',
        permission: 'dealer.specific.discounts',
      },
      {
        id: 'po-management',
        title: 'PO Management',
        icon: FileText,
        path: '/sales-purchase/po-management',
        permission: 'po.management',
      },
      {
        id: 'grn-entry',
        title: 'GRN Entry',
        icon: PackageCheck,
        path: '/sales-purchase/grn-entry',
        permission: 'grn.entry',
      },
      {
        id: 'dealer-invoice',
        title: 'Dealer Invoice',
        icon: Truck,
        path: '/sales-purchase/dealer-invoice',
        permission: 'invoice',
      },
      {
        id: 'supplier-invoice',
        title: 'Supplier Invoice',
        icon: Truck,
        path: '/sales-purchase/supplier-invoice',
        permission: 'invoice',
      },
      {
        id: 'supplier-payments',
        title: 'Supplier Payments',
        icon: CreditCard,
        path: '/sales-purchase/supplier-payments',
        permission: 'payment',
      },
      {
        id: 'dealer-payments',
        title: 'Dealer Payments',
        icon: CreditCard,
        path: '/sales-purchase/dealer-payments',
        permission: 'payment',
      },
      {
        id: 'debit-note',
        title: 'Debit Note',
        icon: FileText,
        path: '/sales-purchase/debit-note',
        permission: 'debit.note',
      },
      {
        id: 'credit-note',
        title: 'Credit Note',
        icon: FileText,
        path: '/sales-purchase/credit-note',
        permission: 'credit.note',
      },
    ],
  },
  inventory: {
    id: 'inventory',
    title: 'Inventory & Warehouse',
    icon: Warehouse,
    hasSubmenu: true,
    modulePermissions: ['inventory.management', 'stock', 'stock.transfer'],
    items: [
      {
        id: 'stock',
        title: 'Stock',
        icon: FolderSync,
        path: '/inventory/stock',
        permission: 'stock',
      },
      {
        id: 'stock-transfer',
        title: 'Stock Transfer',
        icon: FolderSync,
        path: '/inventory/stock-transfer',
        permission: 'stock.transfer',
      },
      {
        id: 'stock-adjustment',
        title: 'Stock Adjustment',
        icon: RefreshCw,
        path: '/inventory/stock-adjustment',
        permission: 'stock.adjustment',
      },
    ],
  },
  hrms: {
    id: 'hrms',
    title: 'HRMS Administration',
    icon: UserCog,
    hasSubmenu: true,
    modulePermissions: ['hrms.management', 'employee.registration', 'attendance.master'],
    items: [
      {
        id: 'employee-registration',
        title: 'Employee Registration',
        icon: ClipboardList,
        path: '/hrms/employee-registration',
        permission: 'employee.registration',
      },
      {
        id: 'geo-attendance',
        title: 'Geo Attendance',
        icon: MapPinCheck,
        path: '/hrms/geo-attendance',
        permission: 'geo.attendance.monitoring',
      },
      {
        id: 'attendance-master',
        title: 'Attendance Master',
        icon: Calendar,
        path: '/hrms/attendance-master',
        permission: 'attendance.master',
      },
      {
        id: 'shift-management',
        title: 'Shift Management',
        icon: Clock,
        path: '/hrms/shift-management',
        permission: 'attendance.master',
      },
      {
        id: 'leave-management',
        title: 'Leave Management',
        icon: Calendar,
        path: '/hrms/leave-management',
        permission: 'attendance.master',
      },
      {
        id: 'salary-processing',
        title: 'Salary Processing',
        icon: DollarSign,
        path: '/hrms/salary-processing',
        permission: 'salary.processing',
      },
      {
        id: 'generate-salary-slip',
        title: 'Generate Salary Slip',
        icon: Receipt,
        path: '/hrms/generate-salary-slip',
        permission: 'generate.salary.slip',
      },
    ],
  },
  finance: {
    id: 'finance',
    title: 'Finance & Accounts',
    icon: FileText,
    hasSubmenu: true,
    modulePermissions: ['finance.management', 'dealer.ledger', 'supplier.ledger'],
    items: [
      {
        id: 'bank-account-master',
        title: 'Bank Account Master',
        icon: Building2,
        path: '/finance/bank-account-master',
        permission: 'finance.management',
      },
      {
        id: 'voucher-entry',
        title: 'Voucher Entry',
        icon: Receipt,
        path: '/finance/voucher-entry',
        permission: 'finance.management',
      },
      {
        id: 'account-master',
        title: 'Account Master',
        icon: BookMarked,
        path: '/finance/account-master',
        permission: 'finance.management',
      },
      {
        id: 'payment-allocation',
        title: 'Payment Allocation',
        icon: CreditCard,
        path: '/finance/payment-allocation',
        permission: 'finance.management',
      },
      {
        id: 'cash-bank-book',
        title: 'Cash/Bank Book',
        icon: Wallet,
        path: '/finance/cash-bank-book',
        permission: 'finance.management',
      },
      {
        id: 'dealer-ledger',
        title: 'Dealer Ledger',
        icon: Users2,
        path: '/finance/dealer-ledger',
        permission: 'dealer.ledger',
      },
      {
        id: 'supplier-ledger',
        title: 'Supplier Ledger',
        icon: Briefcase,
        path: '/finance/supplier-ledger',
        permission: 'supplier.ledger',
      },
      {
        id: 'cheque-management',
        title: 'Cheque Management',
        icon: FileCheck,
        path: '/finance/cheque-management',
        permission: 'cheque.management',
      },
      {
        id: 'auto-reconciliation',
        title: 'Auto Reconciliation',
        icon: RefreshCw,
        path: '/finance/auto-reconciliation',
        permission: 'auto.reconciliation',
      },
    ],
  },
  reports: {
    id: 'reports',
    title: 'Reports & Logs',
    icon: BarChart2,
    hasSubmenu: true,
    modulePermissions: ['reports.management', 'bill.wise.profit', 'activity.logs', 'balance.sheet'],
    items: [
      {
        id: 'profit-analysis',
        title: 'Profit Analysis',
        icon: PieChart,
        hasSubmenu: true,
        modulePermissions: ['bill.wise.profit', 'category.product.gross.margin'],
        items: [
          {
            id: 'bill-wise-profit',
            title: 'Bill-wise Profit',
            icon: FileText,
            path: '/reports/profit-analysis/bill-wise-profit',
            permission: 'bill.wise.profit',
          },
          {
            id: 'category-margin',
            title: 'Category Margin',
            icon: BarChart2,
            path: '/reports/profit-analysis/category-margin',
            permission: 'category.product.gross.margin',
          },
          {
            id: 'deviation-report',
            title: 'Deviation Report',
            icon: TrendingDown,
            path: '/reports/profit-analysis/deviation-report',
            permission: 'sale.vs.purchase.price.deviation',
          },
        ],
      },
      {
        id: 'activity-logs',
        title: 'Activity Logs',
        icon: Activity,
        path: '/reports/activity-logs',
        permission: 'activity.logs',
      },
      {
        id: 'download-logs',
        title: 'Download Logs',
        icon: Download,
        path: '/reports/download-logs',
        permission: 'download.logs',
      },
      {
        id: 'dealer-performance',
        title: 'Dealer Performance',
        icon: LineChart,
        path: '/reports/dealer-performance',
        permission: 'dealer.performance',
      },
      {
        id: 'balance-sheet',
        title: 'Balance Sheet',
        icon: FileText,
        path: '/reports/balance-sheet',
        permission: 'balance.sheet',
      },
      {
        id: 'trial-balance',
        title: 'Trial Balance',
        icon: FileText,
        path: '/reports/trial-balance',
        permission: 'balance.sheet',
      },
      {
        id: 'profit-loss',
        title: 'Profit & Loss',
        icon: FileText,
        path: '/reports/profit-loss',
        permission: 'balance.sheet',
      },
      {
        id: 'gst-reports',
        title: 'GST Reports',
        icon: FileText,
        path: '/reports/gst-reports',
        permission: 'balance.sheet',
      },
      {
        id: 'aging-report',
        title: 'Aging Report',
        icon: FileText,
        path: '/reports/aging-report',
        permission: 'balance.sheet',
      },
      {
        id: 'audit-trail',
        title: 'Audit Trail',
        icon: FileText,
        path: '/reports/audit-trail',
        permission: 'balance.sheet',
      },
    ],
  },
  supplierIncentive: {
    id: 'supplier-incentive',
    title: 'Supplier Incentive',
    icon: Gift,
    hasSubmenu: true,
    modulePermissions: ['supplier.incentive', 'scheme.entry'],
    items: [
      {
        id: 'scheme-entry',
        title: 'Scheme Entry',
        icon: FileText,
        path: '/supplier-incentive/scheme-entry',
        permission: 'scheme.entry',
      },
      {
        id: 'scheme-analysis',
        title: 'Scheme Analysis',
        icon: BarChart2,
        path: '/supplier-incentive/scheme-analysis',
        permission: 'scheme.analysis',
      },
      {
        id: 'claim-submission',
        title: 'Claim Submission',
        icon: ClipboardList,
        path: '/supplier-incentive/claim-submission',
        permission: 'claim.submission',
      },
      {
        id: 'incentive-reconciliation',
        title: 'Reconciliation',
        icon: RefreshCw,
        path: '/supplier-incentive/reconciliation',
        permission: 'incentive.reconciliation',
      },
    ],
  },
  dealerApp: {
    id: 'dealer-app',
    title: 'Dealer App',
    icon: Smartphone,
    hasSubmenu: true,
    modulePermissions: ['support.chat', 'dealer.order.requests'],
    items: [
      {
        id: 'dealer-support-chat',
        title: 'Support Chat',
        icon: MessageCircle,
        path: '/dealer-app/support-chat',
        permission: 'support.chat',
      },
      {
        id: 'dealer-order-requests',
        title: 'Dealer Order Requests',
        icon: ClipboardList,
        path: '/dealer-app/order-requests',
        permission: 'dealer.order.requests',
      },
    ],
  },
  salesExecutive: {
    id: 'sales-executive-app',
    title: 'Sales Executive App',
    icon: Users2,
    hasSubmenu: true,
    modulePermissions: ['sales.executive.app', 'se.attendance.view'],
    items: [
      {
        id: 'se-attendance',
        title: 'Attendance',
        icon: CheckCircle,
        path: '/se-app/attendance',
        permission: 'se.attendance.view',
      },
      {
        id: 'se-dealer-visits',
        title: 'Dealer Visits',
        icon: MapPinCheck,
        path: '/se-app/dealer-visits',
        permission: 'se.attendance.view',
      },
      {
        id: 'se-dealer-assignment',
        title: 'Dealer Assignment',
        icon: Users2,
        path: '/se-app/dealer-assignment',
        permission: 'se.attendance.view',
      },
      {
        id: 'se-route-plan',
        title: 'Route Plan',
        icon: MapPin,
        path: '/se-app/route-plan',
        permission: 'se.route.plan',
      },
      {
        id: 'se-dealer-insights',
        title: 'Dealer Insights',
        icon: TrendingUp,
        path: '/se-app/dealer-insights',
        permission: 'se.dealer.insights',
      },
      {
        id: 'se-collections',
        title: 'Collections',
        icon: Wallet,
        path: '/se-app/collections',
        permission: 'se.collections.view',
      },
      {
        id: 'se-targets',
        title: 'Targets',
        icon: Target,
        path: '/se-app/targets',
        permission: 'se.targets.view',
      },
      {
        id: 'se-expenses',
        title: 'Expenses',
        icon: Receipt,
        path: '/se-app/expenses',
        permission: 'sales.executive.app',
      },
      {
        id: 'se-live-tracking',
        title: 'Live Tracking',
        icon: MapPin,
        path: '/se-app/live-tracking',
        permission: 'sales.executive.app',
      },
    ],
  },
  deliveryExecutive: {
    id: 'delivery-executive-app',
    title: 'Delivery Executive App',
    icon: Truck,
    hasSubmenu: true,
    modulePermissions: ['delivery.executive.app', 'de.assignment.manage'],
    items: [
      {
        id: 'de-assignment',
        title: 'Assignment',
        icon: CheckCircle,
        path: '/de-app/assignment',
        permission: 'de.assignment.manage',
      },
      {
        id: 'de-monitoring',
        title: 'Monitoring',
        icon: Activity,
        path: '/de-app/monitoring',
        permission: 'de.monitoring.view',
      },
      {
        id: 'de-my-deliveries',
        title: 'My Deliveries',
        icon: Truck,
        path: '/de-app/my-deliveries',
        permission: 'de.deliveries.view',
      },
      {
        id: 'de-live-tracking',
        title: 'Live Tracking',
        icon: MapPin,
        path: '/de-app/live-tracking',
        permission: 'de.tracking.view',
      },
      {
        id: 'de-route-plan',
        title: 'Route Plan',
        icon: MapPinCheck,
        path: '/de-app/route-plan',
        permission: 'de.route.view',
      },
      {
        id: 'de-collections',
        title: 'Collections',
        icon: Wallet,
        path: '/de-app/collections',
        permission: 'de.collections.view',
      },
      {
        id: 'de-history',
        title: 'History',
        icon: History,
        path: '/de-app/history',
        permission: 'de.history.view',
      },
    ],
  },
};

/**
 * Role-based section visibility
 * super_admin sees all, others see relevant sections
 */
export const getRoleMenuSections = (role) => {
  const allSections = [
    menuConfig.dashboard,
    menuConfig.system,
    menuConfig.masters,
    menuConfig.salesPurchase,
    menuConfig.inventory,
    menuConfig.hrms,
    menuConfig.finance,
    menuConfig.reports,
    menuConfig.supplierIncentive,
    menuConfig.dealerApp,
    menuConfig.salesExecutive,
    menuConfig.deliveryExecutive,
  ];

  const roleConfigs = {
    super_admin: allSections,
    admin: [
      menuConfig.dashboard,
      menuConfig.system,
      menuConfig.masters,
      menuConfig.salesPurchase,
      menuConfig.inventory,
      menuConfig.hrms,
      menuConfig.finance,
      menuConfig.reports,
      menuConfig.supplierIncentive,
      menuConfig.dealerApp,
      menuConfig.salesExecutive,
    ],
    sub_admin: allSections,
    purchase_manager: [
      menuConfig.dashboard,
      menuConfig.salesPurchase,
      menuConfig.inventory,
      menuConfig.supplierIncentive,
    ],
    hr_manager: [
      menuConfig.dashboard,
      menuConfig.hrms,
    ],
    sales_manager: [
      menuConfig.dashboard,
      menuConfig.masters,
      menuConfig.salesPurchase,
      menuConfig.salesExecutive,
      menuConfig.reports,
    ],
    finance_manager: [
      menuConfig.dashboard,
      menuConfig.finance,
      menuConfig.reports,
    ],
    warehouse_manager: [
      menuConfig.dashboard,
      menuConfig.inventory,
      menuConfig.deliveryExecutive,
    ],
  };

  return roleConfigs[role] || [menuConfig.dashboard];
};

export default menuConfig;
